#!/usr/bin/env bash

git pull --rebase &&
  pip install --upgrade pip &&
  pip install --upgrade -qr requirements.txt &&
  pip install --upgrade -qr devtools.txt &&
  pytest --ignore=ui_tests &&
  behave -t ~@wip -t ~@future &&
  pytest ui_tests &&
  ruff check &&
  bandit -lll --exclude ./venv -r . &&
  cat <<-'HERE'
    ___ _   _  ___ ___ ___ ___ ___
   / __| | | |/ __/ __| __/ __/ __|
   \__ \ |_| | (_| (__| _|\__ \__ \
   |___/\___/ \___\___|___|___/___/

HERE
