#!/usr/bin/env bash

git pull &&
  pip install --upgrade pip &&
  pip install --upgrade -qr requirements.txt &&
  pip install --upgrade -qr devtools.txt &&
  pytest --ignore=ui_tests &&
  behave -t ~@wip -t ~@future &&
  pytest ui_tests
